### ISSUE TITLE
CircleCi API NPM install often fails with ECONNRESET

### ISSUE THREAD

**Issue by sedubois** [OpenCollective/api#311]
E.g https://circleci.com/gh/OpenCollective/api/1439

````
> history@1.17.0 postinstall /home/ubuntu/app/node_modules/history
> node ./npm-scripts/postinstall.js

npm ERR! Linux 3.13.0-83-generic
npm ERR! argv "/home/ubuntu/nvm/versions/node/v5.1.0/bin/node" "/home/ubuntu/nvm/versions/node/v5.1.0/bin/npm" "install"
npm ERR! node v5.1.0
npm ERR! npm  v2.13.5
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
````

Relaunching the build sometimes allows to make it succeed.

Similar description here:
https://discuss.circleci.com/t/npm-install-has-currently-started-failing-for-my-project/2862

**Comment by sedubois** [comment]
This post mentions the hypothesis of something wrong with xvfb but don't know if we use that at all:
https://github.com/thoughtbot/capybara-webkit/issues/540

Also I remember seeing a CircleCi message about a recent upgrade of Ubuntu 14.04 packages, don't know exact date and if any package there could be incriminated.

**Comment by xdamman** [comment]
Apparently using the npm registry over http instead of https solves the issue but I don't like this solution: 
http://stackoverflow.com/questions/29395793/cant-install-anything-with-npm-econnreset-without-proxy

I've also seen this other error happening time to time: 
`Callback called more than once`
Which seems to be solved in a more recent version of npm https://github.com/npm/npm/issues/4169

I would recommend upgrading to the latest version of Ubuntu (we were using the v12 instead of v14) and also upgrading node/npm. That cannot hurt.
